### ISSUE TITLE
Update README.md with dependencies

### ISSUE THREAD

**Issue by scrypt-kitty** [thekroko/uthgard-herald#13]
Setting up environment for docker image and have ran into issues, so I suggest updating README.md to reflect requirements:

install npm
install node (https://nodejs.org/en/download/)
npm install angular
npm install -g angular-cli (unsure of what -g flag is for, but angular-cli states this command: https://github.com/angular/angular-cli#installation)

Any addition info, like required node.js version to run this app, etc. would be great.

**Comment by burfo** [comment]
Node and npm are prerequisites.  I don't think there are version requirements; suggest running the latest stable.

`npm install <module>` will install a module into the local directory.  You should not need to manually install any specific modules if you're just trying to build this app.
`npm install -g <module>` will install a module _globally_.  They recommend installing it globally because you can also use the angular (`ng`) commands to build a new app from the ground up.  I don't _think_ you need to install it globally just to build/serve this app.

Try this:

1. Install Node and NPM.
2. Download the code.
3. Change directory to /herald/
4. Run `npm install`
5. Run `ng serve`

**Comment by scrypt-kitty** [comment]
> Install Node and NPM.
> Download the code.
> Change directory to /herald/
> Run npm install
> Run ng serve

I was missing npm install in /herald/ thanks! Would like to add this to README.md for future contributors.
